### ISSUE TITLE
Crashes on load

### ISSUE THREAD

**Issue by ghost** [DenisMasterHerobrine/ASoD-ExpertMode#5]
Adding this to the current version of the pack results in the game crashing while Loading. 
Also while looking thorough the json for the quest book it would seem that the there are more quests to the base game that would be removed by overwriting.
The scripts that overwrite the original ones are outdated. 

I know you said the current version is probably the last version but I figured I would let you know.

**Comment by DenisMasterHerobrine** [comment]
This Expert Mode is VERY outdated and isn't really usable for the latest version of the modpack. Latest supported version is 1.6.0. After 1.6.0 there is no support for this. A lot of quests is removed after overwriting since I removed a lot of "cheaty" rewards to avoid skipping recipes.
However, you can try to download 1.6.0 and play Expert Mode easily by just throwing with replacing the files. Also note: 1.3.2.1 adds AE2 since Refined Storage system cannot properly autocraft through Expert Mode recipes. (You'll get lots of lags and low TPS on the server).

Closing this since this mode is discontinued.
